version: "3"

services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    container_name: zookeeper-ctn
    ports:
      - '2181:2181'

  kafka:
    image: 'wurstmeister/kafka'
    container_name: kafka-ctn
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13-alpine
    container_name: postgres-ctn
#    volumes:
#      - pg_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres